/**
 * AI Standalone - constants/battle_move_effects.h 模拟
 */

#ifndef GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
#define GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H

#define EFFECT_EXPLOSION 153
#define EFFECT_DREAM_EATER 140
#define EFFECT_RAZOR_WIND 139
#define EFFECT_SKY_ATTACK 141
#define EFFECT_RECHARGE 111
#define EFFECT_SKULL_BASH 110
#define EFFECT_SOLAR_BEAM 116
#define EFFECT_SPIT_UP 82
#define EFFECT_FOCUS_PUNCH 122
#define EFFECT_SUPERPOWER 154
#define EFFECT_ERUPTION 225
#define EFFECT_OVERHEAT 218

#endif // GUARD_CONSTANTS_BATTLE_MOVE_EFFECTS_H
